"""Add payment_id to Purchase

Revision ID: 40554286a59a
Revises: 745ec629938b
Create Date: 2025-11-09 19:39:26.779109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40554286a59a'
down_revision = '745ec629938b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'payments', ['payment_id'], ['id'])
    op.alter_column('users', 'profilePhoto',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('users', 'profilePhotoMimeType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePhotoMimeType', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('users', 'profilePhoto',
               existing_type=sa.String(length=500),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'payment_id')
    # ### end Alembic commands ###
