"""nueva miagracion

Revision ID: 9f56f0914e15
Revises: 356e4e5cad1a
Create Date: 2025-11-06 19:31:28.585563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f56f0914e15'
down_revision = '356e4e5cad1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
