"""Agregar columnas faltantes a la tabla users

Revision ID: d1688c174fe8
Revises: 0f8c51d82a8d
Create Date: 2025-11-01 22:56:15.929699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1688c174fe8'
down_revision = '0f8c51d82a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
