"""Add user category preferences and email notifications

Revision ID: f35cc3868f40
Revises: 53533509121b
Create Date: 2025-11-24 21:03:26.045142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35cc3868f40'
down_revision = '53533509121b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add emailNotifications column to users table
    op.add_column('users', sa.Column('emailNotifications', sa.Boolean(), nullable=False, server_default='true'))

    # Create user_category_preferences table
    op.create_table(
        'user_category_preferences',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('last_notification_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'category_id', name='uq_user_category')
    )

    # Create indexes
    op.create_index(op.f('ix_user_category_preferences_id'), 'user_category_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_category_preferences_user_id'), 'user_category_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_category_preferences_category_id'), 'user_category_preferences', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_user_category_preferences_category_id'), table_name='user_category_preferences')
    op.drop_index(op.f('ix_user_category_preferences_user_id'), table_name='user_category_preferences')
    op.drop_index(op.f('ix_user_category_preferences_id'), table_name='user_category_preferences')

    # Drop table
    op.drop_table('user_category_preferences')

    # Drop column
    op.drop_column('users', 'emailNotifications')
    # ### end Alembic commands ###
