"""Add user profile and mercadopago fields

Revision ID: 2e35c595fa24
Revises: 976efff3a29b
Create Date: 2025-11-10 00:25:55.985757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e35c595fa24'
down_revision = '976efff3a29b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mercadopagoUserId', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mercadopagoPublicKey', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mercadopagoAccessToken', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mercadopagoRefreshToken', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mercadopagoTokenExpires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('isMercadopagoConnected', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('mercadopagoConnectedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mercadopagoEmail', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_mercadopagoUserId'), 'users', ['mercadopagoUserId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mercadopagoUserId'), table_name='users')
    op.drop_column('users', 'mercadopagoEmail')
    op.drop_column('users', 'mercadopagoConnectedAt')
    op.drop_column('users', 'isMercadopagoConnected')
    op.drop_column('users', 'mercadopagoTokenExpires')
    op.drop_column('users', 'mercadopagoRefreshToken')
    op.drop_column('users', 'mercadopagoAccessToken')
    op.drop_column('users', 'mercadopagoPublicKey')
    op.drop_column('users', 'mercadopagoUserId')
    # ### end Alembic commands ###
