"""add_mercadopago_preference_id

Revision ID: 62b1e01c0ec1
Revises: 00286c06795d
Create Date: 2025-11-18 17:44:33.761348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62b1e01c0ec1'
down_revision = '00286c06795d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'multimedia')
    op.add_column('purchases', sa.Column('mercadopago_preference_id', sa.String(length=255), nullable=True))
    op.alter_column('purchases', 'ticket_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_purchases_mercadopago_preference_id'), 'purchases', ['mercadopago_preference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_mercadopago_preference_id'), table_name='purchases')
    op.alter_column('purchases', 'ticket_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('purchases', 'mercadopago_preference_id')
    op.add_column('events', sa.Column('multimedia', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
