"""add cascade delete for promotions

Revision ID: a41d8524fd5e
Revises: 6c5996e80483
Create Date: 2025-11-14 06:22:37.697886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41d8524fd5e'
down_revision = '6c5996e80483'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('promotions_event_id_fkey', 'promotions', type_='foreignkey')
    op.create_foreign_key(None, 'promotions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.create_foreign_key('promotions_event_id_fkey', 'promotions', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
