"""nueva miagracion

Revision ID: 37306d39bde6
Revises: 9f56f0914e15
Create Date: 2025-11-06 21:19:33.926552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37306d39bde6'
down_revision = '9f56f0914e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
